# Generated by Django 2.2 on 2022-01-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhhapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.ImageField(upload_to='trailpics'),
        ),
    ]
