# Generated by Django 2.2 on 2022-01-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhhapp', '0002_auto_20220124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.URLField(),
        ),
    ]
